### ISSUE TITLE
Not working for Catalina

### ISSUE THREAD

**Issue by gfMX** [maxrugen/huesync-remover#5]
HuSync.kext is not on that folder on Catalina, haven't found it yet, ¿Any clues?

**Comment by gfMX** [comment]
I think I found it:
/Library/Audio/Plug-Ins/HAL/HueSyncAudio.driver

**Comment by maxrugen** [comment]
Fixed with https://github.com/maxrugen/huesync-remover/pull/3 thanks to @voxxit 💯
